version: '{build}'

environment:
  matrix:
    - nodejs_version: "8"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm run setup

test_script:
  - node --version
  - npm --version
  - npm test

build: off
